import Head from "next/head";
import { useUser } from "@clerk/nextjs";

import { api } from "~/utils/api";

export default function SinglePostPage() {
  const { isLoaded: userLoaded, isSignedIn } = useUser();

  // start fetching posts early
  api.posts.getAll.useQuery();

  if (!userLoaded) return <div />;

  return (
    <>
      <Head>
        <title>T3-Chat by Moonify</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <p className="text-lg text-white">POST VIEW</p>
        </div>
      </main>
    </>
  );
}
